### ISSUE TITLE
Error on deploying

### ISSUE THREAD

**Issue by damilareolowoniyi** [adamluvshotsauce/lwc-activity-timeline#1]
Hi Adam, 

I was trying to implement Timeline and noticed you did something very similar so i was trying to test your LWC components you've created. When i try to deploy the app i get the following error 

No MODULE named markup://c:outputField found : [markup://c:activityTimeline, markup://c:activityTimelineItem, markup://c:activityTimelineItemDetail] 

I was wondering if you could provide me some guidance on how to resolve this one?

Thanks,
Damilare

**Comment by adamluvshotsauce** [comment]
Hey @damilareolowoniyi sorry about that in a rush to get this implementation tracked in gh I forgot a few missing components (one of them as you mentioned is `c:outputField`). I went ahead and recommitted the project to the repo.

Let me know if you experience any further issues in deploying this project. 

Also, I would like to add in the next coming days I will commit a readme file for how to best implement this component in orgs but in the meantime feel free to reach out to me with any questions.

Thanks,
~Adam

**Comment by damilareolowoniyi** [comment]
Hi it successfully worked. however i wanted to quickly test it on my scratch org. But its showing up as empty when try to drag the activityTimeline component. 

```
<?xml version="1.0" encoding="UTF-8"?>
<LightningComponentBundle xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>51.0</apiVersion>
    <isExposed>true</isExposed>
  <targets>
    <target>lightning__AppPage</target>
    <target>lightning__RecordPage</target>
    <target>lightning__HomePage</target>
  </targets>
</LightningComponentBundle>
```
i'm not sure if you wanted to also add these to the supporting lwc xmls for each component. 

Would be great if you could provide how you could deploy this.

Thanks in advance Adam!
Damilare

**Comment by adamluvshotsauce** [comment]
Ya, it will remain blank until you provide the component with data which will require just a little bit of code which I intentionally left to the discretion of any developer that wanted to use this component.

However, I would like to understand a little bit more about your use case. When I originally designed this component I was using it in a custom app which is why you don't see targets in the corresponding xml files. 

Are you intending on using this on an object record page? If so, how would this differ from the out of box activity history timeline?

I have some ideas on how this can work but I'll like to understand how you intend to use in order to avoid sending you down the wrong path.

**Comment by adamluvshotsauce** [comment]
@damilareolowoniyi I wanted to get back to you on this. 

My original intention was to decouple the wired data from the timeline component in order to develop a more reusable component as I was considering the number of ways this component could be leveraged. So I wanted to walk you through what that process looks like.

1. Let's create a new parent lwc component which we'll call `taskHistory` which we need to define 2 properties  an `@api recordId` and `@track taskHistory = []`. When applied to a lightning record page the `recordId` prop enables the component to automatically receive the Id of the record being view. The `taskHistory` will be an array of task objects from the data provided by an apex method.

2. Create a new apex class or define a `@AuraEnabled` method that returns a list of Tasks by their `WhatId` this will correspond with the `recordId` prop in the `taskHistory` component. For context I will call this method `getTasksByWhatId`.

3. Import the `getTasksByWhatId` method into the `taskHistory` component and call the method to retrieve the task history data into your lwc component.

4. Now this is the important part...when constructing your data objects from the records you retrieved in step 3 you'll have to use a specific schema in order for the components to render the data correctly. 

Here's an example of that schema, you'll want to define, populate with the task data, and push into the `taskHistory` array:
```
{
    "Id": "00T0R00000PkAIWUA3",
    "type": "Task",
    "title": "Meet with Erik Killmonger",
    "description": "We gotta talk about you trying to become the king of Wakanda.",
    "activityDateTime": "2021-03-26T02:43:50.000Z",
    "whatId": "0010R000018WoF3QAK",
    "iconName": "standard:task",
    "creator": {
      "Id": "0050R000007JfGjQAK",
      "Name": "User User"
    },
    "itemDetails": [
      {
        "_id": "WhatId",
        "_name": "Related To",
        "_value": "Wakanda Enterprises",
        "_link": "/lightning/r/0010R000018WoF3QAK/view",
        "_conditional": false
      },
      {
        "_id": "Description",
        "_name": "Description",
        "_value": "We gotta talk about you trying to become the king of Wakanda.",
        "_link": "",
        "_conditional": false
      }
    ],
    "truncate": false
  }
```

Once you populate the `taskHistory` prop with data your `taskHistory` template should look something like this:
```
<template>
    <template if:false={taskHistory}>
        <lightning-spinner alternative-text="Loading" variant="base"></lightning-spinner>
    </template>
    
    <c-activity-timeline title="Task History"
                         activities={taskHistory}
                         placeholder-svg-name="desert"
                         placeholder-heading="No Task History"
                         placeholder-message="There is no task history related to this record."
                         placeholder-size="large">
    </c-activity-timeline>
</template>
```

Then the only thing that is left is to add it to the lightning record page of your choice and it should render an activity timeline that looks something like this:

(Screenshot from a scratch org I deployed and developed using the example I outlined here)
<img width="425" alt="Screen Shot 2021-03-25 at 10 43 58 PM" src="https://user-images.githubusercontent.com/19501793/112587888-a7e2ee00-8dbb-11eb-87ff-60ac8f02c3a9.png">

Hopefully you find this helpful and eventually I will move these steps, appropriately, into the README file for this repo.

**Comment by adamluvshotsauce** [comment]
Hey @damilareolowoniyi I just wanted to follow up since the original issue was related to deployment errors I will close the issue out for now. Feel free to follow up with any additional questions or concerns. Thanks!
